### ISSUE TITLE
Extend errors to include issue reference where possible

### ISSUE THREAD

**Issue by bengsparks** [preslavmihaylov/todocheck#161] opened 2021-08-25 23:55 UTC
The motivation behind this is that related tooling, such as the [todocheck-bot](https://github.com/preslavmihaylov/todocheck/issues/57) can extract the issue number for further actions.
An example thereof would be reopening relevant issues, instead of having to reparse files by the filename and line number that are also in the error message.

After ascertaining that a TODO is valid, we are [guaranteed](https://github.com/preslavmihaylov/todocheck/blob/d24d39d5c0e2c0cf7d19dc0eb8a385833a17cb78/checker/checker.go#L39) to have an issue ref of some form.

This reference could be added to the [TODO](https://github.com/preslavmihaylov/todocheck/blob/d24d39d5c0e2c0cf7d19dc0eb8a385833a17cb78/checker/errors/errors.go#L21) type, which could then be emitted into JSON, and parsed by the todocheck-bot.

**Comment by preslavmihaylov** [comment] 2021-08-29 13:49
Duplicate of #162

**Closed by preslavmihaylov** 2021-08-29 13:49 UTC
